services:
  postgre:
    image: postgres:17-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: dawamr
      POSTGRES_PASSWORD: dawamr
      POSTGRES_DB: 'workorder-tsp'

  go-appcv:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgre
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5532
      DB_USER: 'dawamr'
      DB_PASSWORD: 'dawamr'
      DB_NAME: 'workorder-tsp'
      JWT_SECRET: 'DAWAMRAJA'
      TOKEN_EXPIRES_IN: '24h'
      PORT: '8080'
    ports:
      - '5533:8080'
    restart: always

volumes:
  mysql_data:
