services:
  postgre:
    image: postgres:17-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: dawamr
      POSTGRES_PASSWORD: dawamr
      POSTGRES_DB: 'workorder-tsp'
    networks:
      - workorder-network

  go-appcv:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgre
    env_file:
      - .env
    ports:
      - '5533:8080'
    restart: always
    networks:
      - workorder-network

networks:
  workorder-network:
    driver: bridge
