services:
  workorder-db:
    image: postgres:17-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: dawamr
      POSTGRES_PASSWORD: dawamr
      POSTGRES_DB: 'workorder-tsp'

  workorder-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - workorder-db
    environment:
      DB_HOST: workorder-db
      DB_USER: 'dawamr'
      DB_PASSWORD: 'dawamr'
      DB_NAME: 'workorder-tsp'
    ports:
      - '5533:8080'
    restart: always
